name: WanderWalt
favicon: null
layout_spectrum: 0.57194
typography_spectrum: 0.63699
title: WanderWalt Club
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#daeeed'
    - '#013e75'
    - '#8e8170'
    - '#090000'
    - '#96c4d4'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
