name: WanderWalt
favicon: null
layout_spectrum: 0.00294
typography_spectrum: 0.63699
title: WanderWalt Club
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f2f2'
    - '#1b9298'
    - '#76d9de'
    - '#bdbec0'
    - '#157075'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
